# Generated by Django 3.1.3 on 2020-11-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='items',
            field=models.CharField(max_length=5000),
        ),
    ]
