# Generated by Django 3.1.3 on 2020-11-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='mobile_no',
            field=models.IntegerField(default=0),
        ),
    ]
